services:
  - type: web
    env: node
    name: RLEC
    repo: https://github.com/rONin01010101010/RLEC
    rootDir: .
    region: oregon
    plan: free
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
